### ISSUE TITLE
I am getting this value error. how do i solve it?

### ISSUE THREAD

**Issue by anzosasuke** [Kirito0/bof_aeg#1]
The error i am getting is "ValueError: Make sure ld-linux.so.2 or ld-linux-x86-64.so.2 is in.". I have replaced libpath with my own glibc-all-in-one/2.23-0ubuntu3_amd64 as well. But i can't seem to get rid of this error. Please let me know how i can fix this.
I am using Ubuntu 20.04 LTS.
full error 
```Traceback (most recent call last):
  File "bof_aeg.py", line 537, in <module>
    pwn.ctx.custom_lib_dir = libpath
  File "/home/a967a038/.local/lib/python3.8/site-packages/pwnlib/context/__init__.py", line 176, in fset
    self._tls[name] = validator(self, val)
  File "/usr/local/lib/python3.8/dist-packages/welpwn-0.97-py3.8.egg/PwnContext/core.py", line 172, in custom_lib_dir
    raise ValueError("Make sure ld-linux.so.2 or ld-linux-x86-64.so.2 is in.")
```

**Comment by anzosasuke** [comment]
I solved it
